## Deploy mongodb
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: mongodb-deployment
#  labels:
#    app: mongodb
#spec:
#  replicas: 3
#  selector:
#    matchLabels:
#      app: mongodb
#  template:
#    metadata:
#      labels:
#        app: mongodb
#    spec:
#      containers:
#        - name: mongodb-instance
#          image: mongo:5
#          command:
#            - mongod
#            - "--replSet"
#            - rs0
#            - "--bind_ip_all"
#            - "--port"
#            - "27017"
#
#
