##Configure storage for the mongodb cluster
##Configure PV for storage space
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mongodb-pv
#  labels:
#    app: mongodb
#spec:
#  capacity:
#    storage: 1G
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: /data/mongodb
#---
##Configure PVC for storage claim, this is for data persistency
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mongodb-pvc
#  labels:
#    app: mongodb
#spec:
#  storageClassName: ""
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1G