# argoCD configuration file responsible for the netflix-fe application deployment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yolo5
  namespace: argocd
  finalizers:
    # Delete application related resources when issuing application delete
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/barrotem/PolybotInfra.git
    path: k8s/yolo5
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
