# argoCD configuration file responsible for the netflix-fe application deployment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polybot-app-of-apps
  namespace: argocd
#  finalizers:
#    # Delete application related resources when issuing application delete
#    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/barrotem/PolybotInfra.git
    path: argo/app-of-apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
#  syncPolicy:
#    automated:
#      prune: false
#      selfHeal: false
#      allowEmpty: false